set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btn_S2]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports PC_Uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports PC_Uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN U3 [get_ports {sw_pin[7]}]
set_property PACKAGE_PIN U2 [get_ports {sw_pin[6]}]
set_property PACKAGE_PIN V2 [get_ports {sw_pin[5]}]
set_property PACKAGE_PIN V5 [get_ports {sw_pin[4]}]
set_property PACKAGE_PIN V4 [get_ports {sw_pin[3]}]
set_property PACKAGE_PIN R3 [get_ports {sw_pin[2]}]
set_property PACKAGE_PIN T3 [get_ports {sw_pin[1]}]
set_property PACKAGE_PIN T5 [get_ports {sw_pin[0]}]
set_property PACKAGE_PIN T4 [get_ports PC_Uart_txd]
set_property PACKAGE_PIN R15 [get_ports btn_S2]
set_property PACKAGE_PIN N5 [get_ports PC_Uart_rxd]


