
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_cs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN G6 [get_ports {seg_cs[0]}]
set_property PACKAGE_PIN E1 [get_ports {seg_cs[1]}]
set_property PACKAGE_PIN F1 [get_ports {seg_cs[2]}]
set_property PACKAGE_PIN G1 [get_ports {seg_cs[3]}]
set_property PACKAGE_PIN H1 [get_ports {seg_cs[4]}]
set_property PACKAGE_PIN C1 [get_ports {seg_cs[5]}]
set_property PACKAGE_PIN C2 [get_ports {seg_cs[6]}]
set_property PACKAGE_PIN G2 [get_ports {seg_cs[7]}]
set_property PACKAGE_PIN D4 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN E3 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN D3 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN F4 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN F3 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN E2 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN D2 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN H2 [get_ports {seg_data[7]}]
set_property PACKAGE_PIN B4 [get_ports {seg_data2[0]}]
set_property PACKAGE_PIN A4 [get_ports {seg_data2[1]}]
set_property PACKAGE_PIN A3 [get_ports {seg_data2[2]}]
set_property PACKAGE_PIN B1 [get_ports {seg_data2[3]}]
set_property PACKAGE_PIN A1 [get_ports {seg_data2[4]}]
set_property PACKAGE_PIN B3 [get_ports {seg_data2[5]}]
set_property PACKAGE_PIN B2 [get_ports {seg_data2[6]}]
set_property PACKAGE_PIN D5 [get_ports {seg_data2[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports Signals]
set_property PACKAGE_PIN R17 [get_ports Signals]
set_property PACKAGE_PIN F6 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]




